name: MeineApp
options:
  bundleIdPrefix: com.example
  organizationName: Organization
  deploymentTarget:
    ios: "16.0"

targets:
  MeineApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - MeineApp
    settings:
      PRODUCT_NAME: MeineApp
      BUNDLE_ID: com.example.meineapp
      SWIFT_VERSION: "5.9"
      GENERATE_INFOPLIST_FILE: "YES"
